### PR TITLE
Navigation

### LINKED ISSUE #1: Leucos : Design Navbar
## Task
- Design a navbar for the website 
- Make it responsive for all devices 
- Add a hamburger menu icon for the nav list items when it's responsive 
- Make a small animation on the hamburger menu icon when clicked 

Reference : https://dribbble.com/shots/15752752-Chat-App-Landing-Page ( Try to make it similar to this navbar )

### PR DESCRIPTION
**Pull request by IEdiong**
## Related Issue 

- Info about the related issue 

- [x] KSOC Participant
- [x] Contributor

Closes: #1

### Describe the changes you've made
I added a Navigation bar for both mobile and desktop view. The styles are written in mobile-first approach.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have shared the screenshot with the mentors for verification

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :-----------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
Navbar screenshot | Screen Shot 2022-08-04 at 13 33 04 Screen Shot 2022-08-04 at 13 32 41 Screen Shot 2022-08-03 at 23 33 24

### CODE REVIEW

**Comment by soujo** [comment]
@IEdiong you have made changes in `app.js` and `package-lock.json`
We don't need those changes for the frontend part 
Fix that

**Comment by IEdiong** [comment]
@soujo the change made in `package-lock.json` are not intentional. They came in automatically when I ran `npm install` at the beginning. Please what can I do to solve this.

Also, in the `app.js`, most of the changes were done by my code formatter extension (Prettier). It mostly changes the double quotes to single quotes. The rest are comments.

**Comment by soujo** [comment]
> @soujo the change made in `package-lock.json` are not intentional. They came in automatically when I ran `npm install` at the beginning. Please what can I do to solve this.
> 
> Also, in the `app.js`, most of the changes were done by my code formatter extension (Prettier). It mostly changes the double quotes to single quotes. The rest are comments.

`app,.js` changes can be merged as i reviewed them , but i can't merge `package.json` changes, i don't know what got changed 

`npm i` doesn't changes your  `package.json` , it will only change when you would install some dependencies 

You have to change the  `package.json` as it was earlier

**Comment by soujo** [comment]
@IEdiong , tomorrow is the last day of KSOC , make the required changes in the PR, otherwise we can't accept it

**Pull request closed without merging**
