### PR TITLE
Added Footer

### PR DESCRIPTION
**Pull request by RajavJain**
## Related Issue 

- Info about the related issue 

- [x] KSOC Participant
- [ ] Contributor

Closes: Issue #5 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made
Ran on Local Machine

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original | Updated
Screenshot 2022-07-30 at 18 01 29
 :--------------------: |:-----
Screenshot 2022-07-30 at 18 01 26
---------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by soujo** [comment]
I can't merge this PR , you have changes in `package.json` and `package-lock.json` which is not needed to change the footer.
Also you have made changes in other files also which is not needed 

Make the footer in `views/partials/footer.html` and `static/css/partials/footer.css`
The background should be white , you don't need to write my name there , you can write "Made with love by developers" and add a github icon redirecting to this repo

**Comment by RajavJain** [comment]
Ok I will be creating the new pull request as per the need.

**Comment by RajavJain** [comment]
Can you please help in adding views/partials/footer.ejs file to index.ejs

**Comment by RajavJain** [comment]
Screenshot 2022-07-31 at 02 18 16
Will it work?

**Pull request closed without merging**
