### PR TITLE
added Hero-section #2

### LINKED ISSUE #2: Leucos : Make hero section
## Task 
- Make the hero section for the website

Reference : https://dribbble.com/shots/15752752-Chat-App-Landing-Page

Give the components a small floating animation

### PR DESCRIPTION
**Pull request by Rajarshi12321**
## Related Issue 

- Info about the related issue 

- [x] KSOC Participant
- [x] Contributor

Closes: #2 

### Describe the changes you've made

I have made a simple hero-section.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have shared the screenshot with the mentors for verification

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | image |

### CODE REVIEW

**Comment by Rajarshi12321** [comment]
I have pushed the changes as it was shown in the first screen shot.

**Comment by soujo** [comment]
> I have pushed the changes as it was shown in the first screen shot.

Follow the PR template , make the necessary changes

**Comment by Rajarshi12321** [comment]
I have made this hero-section
image

**Review by Devleena2003 — APPROVED** [review]
Good work!!

**Pull request merged**
