### PR TITLE
added a logo

### LINKED ISSUE #3: Leucos : Redesign the Logo
## Task 
- Redesign the logo for the website 
- Take reference from the internet 
- Don't make it too fancy

### PR DESCRIPTION
**Pull request by SoumaBhuiya**
## Related Issue 

- Info about the related issue 

- [x] KSOC Participant
- [x] Contributor

Closes: #3 

### Describe the changes you've made

I've made a simple logo for this website.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have shared the screenshot with the mentors for verification

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | leucos-logo |

### CODE REVIEW

**Comment by soujo** [comment]
You need to fill up the whole PR template , fill the missing points also

**Comment by SoumaBhuiya** [comment]
> You need to fill up the whole PR template , fill the missing points also

Done

**Comment by soujo** [comment]
> > You need to fill up the whole PR template , fill the missing points also
> 
> Done

You have not made any changes , kindly make the changes in the PR template ( issue linked , changes made , testing ) 
See the PR template has everything , you just need to fill them

**Comment by SoumaBhuiya** [comment]
> > > You need to fill up the whole PR template , fill the missing points also
> > 
> > 
> > Done
> 
> You have not made any changes , kindly make the changes in the PR template ( issue linked , changes made , testing ) See the PR template has everything , you just need to fill them



> > > You need to fill up the whole PR template , fill the missing points also
> > 
> > 
> > Done
> 
> You have not made any changes , kindly make the changes in the PR template ( issue linked , changes made , testing ) See the PR template has everything , you just need to fill them

Now please check.

**Review by soujo — APPROVED** [review]
Good work!

**Comment by SoumaBhuiya** [comment]
> Good work!

Thank You .

**Pull request merged**
